# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb20c1f06df2796d36589dad90127821ac805a82f888e886fa9f8c2a71470dde2dcf635ac0a54703f6f818b4e345e43ff53229ef2f9973648aa060424f426d46

test:
  secret_key_base: 9d876f698466aaf282656d88cb04535e4ace93bbab644f5eaf07160d01db60edcd892642f5fdbde5c64dd7f7b23ac21c3924990ac9f53c4ad5d41270bf121a33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
